variables:
  colors:
    primaryColor1: 3A3A3A
    primaryColor2: 5A5A5A
    primaryColor3: CCCCCC
    primaryColor4: 1A1A1A
    primaryColor5: 9A9A9A
  fonts:
    defaultHeaderFont: georgia
    defaultBodyFont: helvetica
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://favicon-0.png'
favicon:
  use_default: false
  path: 'public://favicon.ico'
  mimetype: image/vnd.microsoft.icon
omega_toggle_intro: 1
enable_backups: 0
force_subtheme_creation: 0
block_demo_mode: 1
screen_demo_indicator: 1
default_layout: primary
home_layout: primary
enable_omegags_layout: 1
layouts: {  }
breakpoint_group_primary: omegaout.default
node_type_article_layout: primary
node_type_page_layout: primary
taxonomy_category_layout: primary
taxonomy_tags_layout: primary
edit_this_layout: primary
_core:
  default_config_hash: qw5XkxuQACZS3WyP8XJkX58EvWyaY4ryo9vHaTUVlnQ
compile_scss: 1
show_compile_warning: 1
enable_omega_badge: 1
styles:
  omegaout/omegaout: 1
  omega/omega: 1
  omega/omega_html_elements: 1
  omega/omega_branding: 1
  omega/omega_breadcrumbs: 1
  omega/omega_main_menus: 1
  omega/omega_messages: 1
  omega/omega_pagers: 1
  omega/omega_tabs: 1
  omega/omega_taxonomy_terms: 1
  omega/omega_forms: 1
  omega_simple_starterkit/omega_simple_starterkit: 1
layout-config:
  non_omegags_info: ''
node_type_blog_layout: primary
node_type_test_layout: primary
taxonomy_categories_layout: primary
taxonomy_job_role_layout: primary
