button_option: stbc_vcount
comments: 0
late_load: 0
location: content
node_types:
  blog: blog
  article: null
  page: null
  test: null
option_extras:
  'Facebook Like:fblike': 'Facebook Like:fblike'
  'Google Plus One:plusone': '0'
option_neworzero: 0
option_onhover: 1
option_shorten: 1
service_option: '''Facebook:facebook'',''Email:email'''
twitter_handle: ''
twitter_recommends: ''
twitter_suffix: ''
webform_options: ''
weight: 10
widget_option: st_multi
cns:
  donotcopy: null
  hashaddress: null
sharethisnodes:
  article:
    full: full
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
  page:
    full: full
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
  blog:
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
  test:
    full: '0'
    rss: '0'
    search_index: '0'
    search_result: '0'
    teaser: '0'
_core:
  default_config_hash: OUePCWmQ_tUOCD4VF7-AP0maPJi2Y18f0JvNTgThhRQ
publisherID: dr-72436598-8b41-7d5c-4cdc-4a6c5c8d36e
callesi: '0'
